config/routes.rb
Rails.application.routes.draw do

  get '/admin' => 'admin#index'
  put '/admin/:id' => 'admin#update'
  patch '/admin/:id' => 'admin#update'


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :apartments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'apartments#homepage'
  post 'apartments/find'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      # if no user logged in, use a dummy user, see later
      user = User.new
    end
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :manager
      can :manage, Apartment
    elsif user.has_role? :renter
      can :read, :all
    end
  end
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, presence: true,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }
  belongs_to :user
  validates :user, presence: true

  resourcify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :apartments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  after_create :assign_role

         def assign_role
           add_role(:renter)
         end

         def self.from_omniauth(auth)
           where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
             user.email = auth.info.email
             user.password = Devise.friendly_token[0,20]

             # If you are using confirmable and the provider(s) you use validate emails,
             # uncomment the line below to skip the confirmation emails.
             # user.skip_confirmation!
           end
         end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize

  #get "admin"
  def index
    @users = User.all
  end
  #put/patch "admin/:id"
  def update
    user = User.find(params[:id])
    user.remove_role user.roles.last
    user.add_role(:manager)
    redirect_to '/admin'
  end

private

def authorize
   if !current_user.has_role? :admin
     render plain "No access for you!"
   end
 end

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
    @ability = Ability.new(current_user)
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  def homepage
    render 'homepage.html.erb'
  end

  def full_address

  end

  def find
    @search_results = Apartment.basic_search( street1: params[:street], city: params[:city])
    @apartment = @search_results.first
    #Above returns an ARRAY, @apartment.id doesn't work, but @apartment.first.id does work.
    @id = @apartment.id
    redirect_to "/apartments/#{@id}"

  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new(user_id: current_user.id)
    # @apartment.user_id = current_user.id
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:street1, :street2, :city, :zipcode, :state, :country, :name, :phone, :hours, :image, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

<h1>Users</h1>
<table>
  <thead>
    <thead>
      <tr>
        <th>Email</th><th>Role</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <%= form_tag("/admin/" + user.id.to_s + "?role=manager", method: :PUT) do %>
          <input type="submit" value="Make Manager"/>
        <% end %>
      </td>
      <td> <%=user.roles.last.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true, html: { multipart: true } )  do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :street1 %>
    <%= form.text_field :street1, id: :apartment_street1 %>
  </div>

  <div class="field">
    <%= form.label :street2 %>
    <%= form.text_field :street2, id: :apartment_street2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :apartment_city %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.number_field :zipcode, id: :apartment_zipcode %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :apartment_state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :apartment_country %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :apartment_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :apartment_phone %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.time_select :hours, id: :apartment_hours %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>

  <p>
    <%= if !current_user.nil?
          current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
        end
    %>
  </p>




<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/homepage.html.erb
<h1>Welcome to Apartment Listings</h1>
<form action="apartments/find" method="post">
  <input type="text" name="street" placeholder="Street">
  <input type="text" name="city" placeholder="City">
  <input type="submit" name="" value="Find Apartment">
</form>

<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Street1</th>
      <th>Street2</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>State</th>
      <th>Country</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.street1 %></td>
        <td><%= apartment.street2 %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.zipcode %></td>
        <td><%= apartment.state %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.name %></td>
        <td><%= apartment.phone %></td>
        <td><%= apartment.hours %></td>
        <td><%= link_to 'Show', apartment %></td>
        <% if @ability.can? :manage, Apartment %>
          <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
          <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Apartment', new_apartment_path %>

<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <title>Google Maps Multiple Markers</title>
  <script src="http://maps.google.com/maps/api/js?sensor=false"
          type="text/javascript"></script>
</head>
<body>
  <div id="map" style="width: 500px; height: 400px;"></div>

  <script type="text/javascript">
    var locations = [
      ['Learn Academy', 32.709630, -117.158017, 1],
      ['Amy Austin House', 30.271526, -97.784571, 5],
      ['Sandro House', 33.008461, -117.116217, 3],

    ];

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 8,
      center: new google.maps.LatLng(33.008461, -117.116217),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  </script>
</body>
</html>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street1:</strong>
  <strong  id = "location">
    <%= @apartment.street1 %>
  </strong>
</p>

<p>
  <strong>Street2:</strong>
  <%= @apartment.street2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @apartment.zipcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @apartment.phone %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @apartment.hours %>
</p>

<%= link_to image_tag(@apartment.image.url(:large)), @apartment.image.url %>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>


<!DOCTYPE html>
<html>
  <head>
    <title>Geocoding service</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
      <input id="address" type="hidden" value='<%= @apartment.street1 %>,  <%= @apartment.street2 %>
,  <%= @apartment.city %>,  <%= @apartment.state %>'>
    <div id="map"></div>
    <script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 8,
          center: {lat: -34.397, lng: 150.644}
        });
        var geocoder = new google.maps.Geocoder();

         function geocodeme() {
          geocodeAddress(geocoder, map);
        };
        geocodeme();
      }

      function geocodeAddress(geocoder, resultsMap) {

        var address = document.getElementById('address').value;
        geocoder.geocode({'address': address}, function(results, status) {
          if (status === 'OK') {
            resultsMap.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
              map: resultsMap,
              position: results[0].geometry.location
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5xGHKvmq2Cqus8xA9odozLbnRBRRyy_E&callback=initMap">
    </script>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AptApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>